### ISSUE TITLE
problem when creating  a new API client

### ISSUE THREAD

**Issue by BOTI-david** [radyakin/susoapi#17]
@radyakin #16 
when running SuSo API from stata, I get the following error after running the command line in stata 
.t=.SuSo.new server login password.
Is my specification for creating a client API correct? if so what is the problem...I am new to Python programming. thanks for your help
![Inkederreur2_LI](https://user-images.githubusercontent.com/90085333/132623228-b49f1363-7bc9-42da-8fd6-83254a2067cf.jpg)

_Originally posted by @BOTI-david in https://github.com/radyakin/susoapi/issues/16#issuecomment-915757386_

**Comment by radyakin** [comment]
1. Which version of the code resulted in this error message? The one published in SSC or the current one in this repository?

2. Please retry with the version published here in this repository by downloading and replacing the SuSo.class and SuSoBase.class files and restarting Stata afterwards. Please do let know if this helped.

3. There was a similar issue:
https://github.com/radyakin/susoapi/issues/12
It is important to know whether the user is given permissions on the server. What workspaces are defined and what permissions are given to this user?

4. Try to login using admin credentials and see if it makes any difference.

**Comment by radyakin** [comment]
The problem has been reproduced with the SSC-released version and the incorrect credentials specified during initiation of the API client (for the same version of the Survey Solutions server).

![image](https://user-images.githubusercontent.com/52933296/145826254-108eae19-7906-468d-95a0-a8b31d1b1171.png)

The issue is attributed to the problem with authentication data, not with the API client code.
